a= float(input('a = '))
b= float(input('b = '))
print ('Tổng là : ', a+b)
print ('Hiệu là : ', a-b)
print ('Tích là : ', a*b)
print ('Thương là : ', a/b)
print ('Phần nguyên là : ', a//b)
print ('Phần dư là : ', a%b)
print ('Lũy thừa là : ', a**b)

